#!/usr/bin/env bash

# Current directory.
__dirname="$(dirname "${BASH_SOURCE[0]}")";

# Create symlinks in home directory.
for dotfile in "$__dirname"/.*; do
  if [[ -f "$dotfile" ]]; then
    ln -sf "$dotfile" ~/"$(basename "$dotfile")";
  fi;
done;
